In [5]:
import pandas as pd
import numpy as np
import json
import csv

In [6]:
data = pd.read_csv("battery_evaluate_ouput.csv")

In [7]:
data

,max_nopower_count,Evaluate Score,name,max_cap,other_info,year_round_status,current_cap
0,9,0,"[""Ultimate Power 12V 100Ah Lithium-Ion (LiFePO...",39.20,"[{""name"": ""Ultimate Power 12V 100Ah Lithium-Io...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[39.2, 38.78126529240186, 38.566211528961006, ..."
1,7,0,"[""Discover AES 7.4 kWh"", ""Discover AES 7.4 kWh...",42.75,"[{""name"": ""Discover AES 7.4 kWh"", ""max_recharg...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[42.75000000000001, 42.34008075993025, 42.1295..."
2,7,0,"[""Discover AES 7.4 kWh"", ""Discover AES 7.4 kWh...",42.15,"[{""name"": ""Discover AES 7.4 kWh"", ""max_recharg...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[42.150000000000006, 41.74008075993025, 41.529..."
3,9,0,"[""Discover AES 7.4 kWh"", ""Discover AES 7.4 kWh...",41.55,"[{""name"": ""Discover AES 7.4 kWh"", ""max_recharg...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[41.550000000000004, 41.14008075993025, 40.929..."
4,7,0,"[""Discover AES 7.4 kWh"", ""Discover AES 7.4 kWh...",43.70,"[{""name"": ""Discover AES 7.4 kWh"", ""max_recharg...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[43.7, 43.29008075993025, 43.079554444140776, ..."
...,...,...,...,...,...,...,...
12952,8,0,"[""Tesla Powerwall+ "", ""Tesla Powerwall+ "", ""Te...",56.30,"[{""name"": ""Tesla Powerwall+ "", ""max_recharge_r...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[56.300000000000004, 55.86730746881526, 55.645..."
12953,8,0,"[""Tesla Powerwall+ "", ""Tesla Powerwall+ "", ""Te...",56.20,"[{""name"": ""Tesla Powerwall+ "", ""max_recharge_r...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[56.2, 55.76730746881526, 55.54508524659304, 5..."
12954,8,0,"[""Tesla Powerwall+ "", ""Tesla Powerwall+ "", ""Te...",54.20,"[{""name"": ""Tesla Powerwall+ "", ""max_recharge_r...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[54.2, 53.76730746881526, 53.54508524659304, 5..."
12955,8,0,"[""Tesla Powerwall+ "", ""Tesla Powerwall+ "", ""Te...",54.10,"[{""name"": ""Tesla Powerwall+ "", ""max_recharge_r...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[54.1, 53.66730746881526, 53.44508524659304, 5..."
12956,8,0,"[""Tesla Powerwall+ "", ""Tesla Powerwall+ "", ""Te...",58.30,"[{""name"": ""Tesla Powerwall+ "", ""max_recharge_r...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[58.300000000000004, 57.86730746881526, 57.645..."

In [66]:
data.sort_values(by=["max_cap"])

,max_nopower_count,Evaluate Score,name,max_cap,other_info,year_round_status,current_cap
16,10,0,"[""Electriq PowerPod 2"", ""Electriq PowerPod 2"",...",39.00,"[{""name"": ""Electriq PowerPod 2"", ""max_recharge...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[39.0, 38.59435075201431, 38.38601741868097, 3..."
58,10,0,"[""Deka Solar 8GCC2 6V 198"", ""Electriq PowerPod...",39.05,"[{""name"": ""Deka Solar 8GCC2 6V 198"", ""max_rech...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[39.050000000000004, 38.59435075201431, 38.386..."
404,10,0,"[""Deka Solar 8GCC2 6V 198"", ""Deka Solar 8GCC2 ...",39.10,"[{""name"": ""Deka Solar 8GCC2 6V 198"", ""max_rech...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[39.1, 38.59435075201431, 38.38601741868097, 3..."
1955,10,0,"[""Deka Solar 8GCC2 6V 198"", ""Deka Solar 8GCC2 ...",39.15,"[{""name"": ""Deka Solar 8GCC2 6V 198"", ""max_rech...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[39.15, 38.59435075201431, 38.38601741868097, ..."
78,10,0,"[""Trojan L-16 -SPRE 6V 415"", ""Electriq PowerPo...",39.19,"[{""name"": ""Trojan L-16 -SPRE 6V 415"", ""max_rec...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[39.190000000000005, 38.59435075201431, 38.386..."
...,...,...,...,...,...,...,...
12026,0,0,"[""Discover AES 7.4 kWh"", ""Electriq PowerPod 2""...",74.45,"[{""name"": ""Discover AES 7.4 kWh"", ""max_recharg...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[74.45, 74.04008075993025, 73.82955444414078, ..."
12412,0,0,"[""Electriq PowerPod 2"", ""Electriq PowerPod 2"",...",74.80,"[{""name"": ""Electriq PowerPod 2"", ""max_recharge...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[74.80000000000001, 74.3943507520143, 74.18601..."
12027,0,0,"[""Discover AES 7.4 kWh"", ""Electriq PowerPod 2""...",75.05,"[{""name"": ""Discover AES 7.4 kWh"", ""max_recharg...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[75.05, 74.64008075993024, 74.42955444414078, ..."
12407,0,0,"[""Electriq PowerPod 2"", ""Electriq PowerPod 2"",...",75.40,"[{""name"": ""Electriq PowerPod 2"", ""max_recharge...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[75.4, 74.99435075201431, 74.78601741868097, 7..."
12408,0,0,"[""Electriq PowerPod 2"", ""Electriq PowerPod 2"",...",76.00,"[{""name"": ""Electriq PowerPod 2"", ""max_recharge...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[76.0, 75.59435075201431, 75.38601741868096, 7..."

In [19]:
below2_1k = []
below2_2k = []
below2_3k = []
other2 = []
below5_1k = []
below5_2k = []
below5_3k = []
other5 = []
below10_1k = []
below10_2k = []
below10_3k = []
other10 = []
other = []

bound = [30000, 60000, 90000]

min_cost = 100000
for i in data.sort_values(by=["max_nopower_count"]).T:
    k = json.loads(data.values[i][4])
    cost = sum([c["cost"] for c in k])
    if data.values[i][0] <= 2:
        if cost <= bound[0]:
            below2_1k.append(data.values[i])
        elif bound[0]<cost<=bound[1]:
            below2_2k.append(data.values[i])
        elif bound[1]<cost<=bound[2]:
            below2_3k.append(data.values[i])
        else:
            other2.append(data.values[i])
    elif 2< data.values[i][0] <= 5:
        if cost <= bound[0]:
            below5_1k.append(data.values[i])
        elif bound[0]<cost<=bound[1]:
            below5_2k.append(data.values[i])
        elif bound[1]<cost<=bound[2]:
            below5_3k.append(data.values[i])
        else:
            other5.append(data.values[i])
    elif 5< data.values[i][0] <= 10:
        if cost <= bound[0]:
            below10_1k.append(data.values[i])
        elif bound[0]<cost<=bound[1]:
            below10_2k.append(data.values[i])
        elif bound[1]<cost<=bound[2]:
            below10_3k.append(data.values[i])
        else:
            other10.append(data.values[i])
    else:
        other.append(data.values[i])

In [41]:
base = "/Users/lishuyu/Downloads/"
with open(f"{base}10_3.txt", "w") as f:
    f.write(str(below10_3k))

In [45]:
below2_1k = []
below2_2k = []
below2_3k = []
other2 = []
below5_1k = []
below5_2k = []
below5_3k = []
other5 = []
below10_1k = []
below10_2k = []
below10_3k = []
other10 = []
other = []

bound = [30000, 60000, 90000]

min_cost = 100000
count = 0
max_length = len(data)
for i in data.sort_values(by=["max_nopower_count"]).T:
    count += 1
    data_cache = data.values[i]
    k = json.loads(data_cache[4])
    cost = sum([c["cost"] for c in k])
    if data_cache[0] <= 2:
        if cost <= bound[0]:
            below2_1k.append(data_cache[2])
        elif bound[0]<cost<=bound[1]:
            below2_2k.append(data_cache[2])
        elif bound[1]<cost<=bound[2]:
            below2_3k.append(data_cache[2])
        else:
            other2.append(data_cache[2])
    elif 2< data_cache[0] <= 5:
        if cost <= bound[0]:
            below5_1k.append(data_cache[2])
        elif bound[0]<cost<=bound[1]:
            below5_2k.append(data_cache[2])
        elif bound[1]<cost<=bound[2]:
            below5_3k.append(data_cache[2])
        else:
            other5.append(data_cache[2])
    elif 5< data_cache[0] <= 10:
        if cost <= bound[0]:
            below10_1k.append(data_cache[2])
        elif bound[0]<cost<=bound[1]:
            below10_2k.append(data_cache[2])
        elif bound[1]<cost<=bound[2]:
            below10_3k.append(data_cache[2])
        else:
            other10.append(data_cache[2])
    else:
        other.append(data_cache[2])
    if count % 100 == 0:
        print(count/max_length, "%")

100 12957
200 12957
300 12957
400 12957
500 12957
600 12957
700 12957
800 12957
900 12957
1000 12957
1100 12957
1200 12957
1300 12957
1400 12957
1500 12957
1600 12957
1700 12957
1800 12957
1900 12957
2000 12957
2100 12957
2200 12957
2300 12957
2400 12957
2500 12957
2600 12957
2700 12957
2800 12957
2900 12957
3000 12957
3100 12957
3200 12957
3300 12957
3400 12957
3500 12957
3600 12957
3700 12957
3800 12957
3900 12957
4000 12957
4100 12957
4200 12957
4300 12957
4400 12957
4500 12957
4600 12957
4700 12957
4800 12957
4900 12957
5000 12957
5100 12957
5200 12957
5300 12957
5400 12957
5500 12957
5600 12957
5700 12957
5800 12957
5900 12957
6000 12957
6100 12957
6200 12957
6300 12957
6400 12957
6500 12957
6600 12957
6700 12957
6800 12957
6900 12957
7000 12957
7100 12957
7200 12957
7300 12957
7400 12957
7500 12957
7600 12957
7700 12957
7800 12957
7900 12957
8000 12957
8100 12957
8200 12957
8300 12957
8400 12957
8500 12957
8600 12957
8700 12957
8800 12957
8900 12957
9000 12957
9100 12957
9200 12957
9300 12957
9400 12957
9500 12957
9600 12957
9700 12957
9800 12957
9900 12957
10000 12957
10100 12957
10200 12957
10300 12957
10400 12957
10500 12957
10600 12957
10700 12957
10800 12957
10900 12957
11000 12957
11100 12957
11200 12957
11300 12957
11400 12957
11500 12957
11600 12957
11700 12957
11800 12957
11900 12957
12000 12957
12100 12957
12200 12957
12300 12957
12400 12957
12500 12957
12600 12957
12700 12957
12800 12957
12900 12957

In [47]:
base = "/Users/lishuyu/Downloads/"
with open(f"{base}2_1_name.txt", "w") as f:
    f.write(str("\n".join(below2_1k)))
with open(f"{base}2_2_name.txt", "w") as f:
    f.write(str("\n".join(below2_2k)))
with open(f"{base}2_3_name.txt", "w") as f:
    f.write(str("\n".join(below2_3k)))
with open(f"{base}5_1_name.txt", "w") as f:
    f.write(str("\n".join(below5_1k)))
with open(f"{base}5_2_name.txt", "w") as f:
    f.write(str("\n".join(below5_2k)))
with open(f"{base}5_3_name.txt", "w") as f:
    f.write(str("\n".join(below5_3k)))
with open(f"{base}10_1_name.txt", "w") as f:
    f.write(str("\n".join(below10_1k)))
with open(f"{base}10_2_name.txt", "w") as f:
    f.write(str("\n".join(below10_2k)))
with open(f"{base}10_3_name.txt", "w") as f:
    f.write(str("\n".join(below10_3k)))

In [48]:
import pyperclip

In [61]:
pyperclip.copy(str(below10_3k))

In [68]:
len(below10_2k)

2227

In [ ]:
cost = []
for i in dic:
    cost.append(i["cost"])

In [ ]:
sum(cost)